var itemNamesCN = {
    '1 Day-Old Baguette': '放了一天的法棍面包',
    '69 Charm': '69护符',
    '8 Old Accessories Glued Together': '8个旧饰品的粘合体',
    'A 10 Litre Hat': '牛仔帽',
    'A 9mm Beretta': '伯莱塔9毫米手枪',
    'A Bag of Trash': '一袋垃圾',
    'A Bald Egg': '无毛蛋',
    'A Bandana': '摇滚方巾',
    'A Battle Corgi': '柯基战犬',
    'A Beanie': '冷帽',
    'A Beard Comb': '胡须梳',
    'A Bed Rock': '床之岩',
    'A Bit of White Powder': '一些白色粉末',
    'A Broken Pair Of Scissors': '断了的剪',
    'A Broomstick': '飞天扫帚',
    'A Cheap Plastic Amulet': '廉价的塑料项链',
    'A Comically Oversized Minute-Hand': '大到夸张的分针',
    'A Compass!': '罗盘！',
    'A Corrupted Leaf': '数据损坏的叶子',
    'A Crappy Tutu': '劣质的芭蕾舞裙',
    'A Cream Pie': '奶油派',
    'A Duck Caller': '鸭叫装置',
    'A Dutch Hat': '荷兰帽',
    'A Fake Duckbill': '假鸭嘴兽',
    'A Funky Klein Bottle': '有趣的克莱因瓶',
    'A Garrote': '螺环绞具',
    'A Gas Giant': '气体巨星',
    'A Giant Apple': '大苹果',
    'A Giant Bazooka': '巨型火箭炮',
    'A Giant Scythe': '巨型镰刀',
    'A Giant Wrecking Ball': '巨型落锤',
    'A Gigantic Zipper': '巨大的拉链',
    'A Hand Cursor': '手型光标',
    'A Hardhat': '安全帽',
    'A Level Level': 'A级水平仪',
    'A Link Cable': '联机线',
    'A Manhole': '窨井',
    'A Pet Rock': '宠物石',
    'A Pink Bandana': '粉色方巾',
    'A Power Pill': '能量豆',
    'A Pretty Pink Bow': '粉红蝴蝶结',
    'A Priceless Van-Gogh Painting': '价值连城的梵高画作',
    'A Red Shirt': '红色衬衫',
    'A Regular Tie': '普通领带',
    'A Rocket': '火箭石弹',
    'A Roll of Toilet Paper': '布感手纸',
    'A Rolling Pin': '擀面杖',
    'A Rolling Stone': '滚石',
    'A Rusty Old Sabre': '生锈的旧剑',
    'A Shoe.': '一只鞋子。',
    'A Shrunken Voodoo Doll': '皱缩的巫毒娃娃',
    'A Sinusoidal Wave': '正弦波',
    'A Skateboard': '滑板',
    'A Skipping Stone': '水漂石',
    'A Small Gerbil': '小沙鼠',
    'A Spoonful of Yeast': '一勺酵母',
    'A Stick': '一根木棍',
    'A Triangle': '三角形',
    'A Vinyl Record Shard': '黑胶唱片碎片',
    'A Walkman': '随身听',
    'A Wooden Hammer': '木锤',
    'A Worn Out Fedora': '破旧的绅士帽',
    'A handful of Krazy Bonez': '疯狂骨头玩具套件',
    'A shotgun': '猎枪',
    'AAA Battery Legs': '7号电池护腿',
    'Alarm Clock': '闹钟',
    'Amplifier': '功放',
    'Amulet of Sunshine, Sparkles, and Gore': '阳光、火花和血泊的项链',
    'An Inanimate Carbon Rod': '惰性碳棒',
    'An Infinitely Long Strand of Beard Hair': '一根无限长的胡须',
    'An Inflatable Ducky Innertube': '充气鸭鸭游泳圈',
    'An Ordinary Apple': '普通的苹果',
    'An Ordinary Calculator': '普通的计算器',
    'Anime Bodypillow': '动漫等身抱枕',
    'Anime Figurine': '动漫手办',
    'Anime Hero Wig': '动漫英雄假发',
    'Antennae of the Exile': '被流放者的触角',
    'Antlers of the Exile': '被流放者的鹿角',
    'Ascended Ascended Ascended Pendant': '升变升变升变吊坠',
    'Ascended Ascended Forest Pendant': '升变升变森林吊坠',
    'Ascended Forest Pendant': '升变森林吊坠',
    'Ascended x4 Pendant': '四重升变吊坠',
    'Ascended x5 Pendant': '五重升变吊坠',
    'Ascended x6 Pendant': '六重升变吊坠',
    'Ascended x7 Pendant': '七重升变吊坠',
    'Ascended x8 Pendant': '八重升变吊坠',
    'Ascended x9 Pendant': '九重升变吊坠',
    'Assful Chaps': '牛仔皮套裤',
    'Asslest Vest': '牛仔马甲',
    'BOTH Edgy Boots': '整双锐利靴子',
    'Badly Drawn Chest': '涂鸦护胸',
    'Badly Drawn Foot': '涂鸦之足',
    'Badly Drawn Gun': '涂鸦之枪',
    'Badly Drawn Pants': '涂鸦裤子',
    'Badly Drawn Smiley Face': '涂鸦笑脸',
    'Beam Laser Sword': '光束光剑',
    'Bearded Axe': '胡之斧',
    'Bell Bottoms': '喇叭裤',
    'Black Tulip': '黑郁金香',
    'Bloody Cleaver': '血之菜刀',
    'Blue Cheese Helmet': '蓝纹奶酪头盔',
    'Blue Eyes Ultimate Chestplate': '青眼究极护胸',
    'Blue Eyes White Chestplate': '青眼白护胸',
    'Booms': '轰',
    'Braided Beard Legs': '胡须辫护腿',
    'Brass Knuckles': '铜指虎',
    'Bread Bowl Helmet': '面包碗头盔',
    'Broken Drum': '破鼓',
    'Buster Sword Bottom': '破坏剑底部',
    'Buster Sword Lower': '破坏剑下部',
    'Buster Sword Top': '破坏剑顶部',
    'Buster Sword Upper': '破坏剑上部',
    'Buster of the Exile': '被流放者的飞弹',
    'Candy Corn Necklace': '玉米糖项链',
    'Cement Boots': '水泥靴子',
    'Cheddar Amulet': '切达干酪项链',
    'Cheese Grater': '奶酪刨',
    'Chess Plate': '象棋棋盘',
    'Chocolate Boots': '巧克力靴子',
    'Chocolate Chest': '巧克力护胸',
    'Chocolate Crowbar': '巧克力撬棍',
    'Chocolate Helmet': '巧克力头盔',
    'Chocolate Pants': '巧克力裤子',
    'Choffice Hat of Greed': '厨师办公贪婪帽',
    'Circle Helmet': '圆之头盔',
    'Clockwork Boots': '钟表靴子',
    'Clockwork Chest': '钟表护胸',
    'Clockwork Hat': '钟表之帽',
    'Clockwork Pants': '钟表裤子',
    'Clogs': '木鞋',
    'Cloth Boots': '织物之靴',
    'Cloth Hat': '织物之帽',
    'Cloth Leggings': '织物护腿',
    'Cloth Shirt': '织物衬衫',
    'Clown Hat': '小丑之帽',
    'Combat Cheese': '应战的奶酪',
    'Cool Shades': '酷墨镜',
    'Cracked Amulet': '破碎的项链',
    'Crappy Boots': '劣质靴子',
    'Crappy Chestplate': '劣质护胸',
    'Crappy Helmet': '劣质头盔',
    'Crappy Leggings': '劣质护腿',
    'Creepy Doll': '可怖娃娃',
    'Cursed Ring': '诅咒戒指',
    'Demonic Flurbie Chestplate': '恶魔弗罗比护胸',
    'Disco Ball Helmet': '迪斯科球头盔',
    'Disco Shirt': '迪斯科衬衫',
    'Dorky Glasses': '呆瓜眼镜',
    'Dragon Wings': '龙翼',
    'Duck Duck Shorts': '鸭鸭短裤',
    'Duck Slippers': '鸭鸭拖鞋',
    'Dunce Cap': '邓斯高帽',
    'Edgy Chest': '锐利护胸',
    'Edgy Helmet': '锐利头盔',
    'Edgy Jaw Axe': '锐利双刃斧',
    'Edgy Magicite Crystal': '锐利魔导水晶',
    'Edgy Pants': '锐利裤子',
    'Emperor Looty': '战利品者大帝',
    'Energy Bar Bar': '能量条条',
    'Evil Rubber Ducky': '邪恶的橡皮鸭',
    'Extra Spiky Spurs': '额外的尖马刺',
    'Eye of ELXU': '埃尔许之眼',
    'Fabulous Super Chest': '绝妙的超人护胸',
    'Fanny Pack': '腰包',
    'Floppy Elastic Ruler': '软皮尺',
    'Flour Sack Pants': '面粉袋裤子',
    'Forest Boots': '森林靴子',
    'Forest Chestplate': '森林护胸',
    'Forest Helmet': '森林头盔',
    'Forest Leggings': '森林护腿',
    'Forest Pendant': '森林吊坠',
    'Fuzzy Boots': '毛茸茸靴子',
    'Fuzzy Orange Cheeto Slippers!': '橙色绒毛拖鞋！',
    'GALACTIC HERALD LOOTY': '战利品者银河信使',
    'GRAND DEMON LOOTZIFER': '战利品者大恶魔掠西法',
    'Gaudy Boots': '花哨靴子',
    'Gaudy Epaulettes': '花哨肩章',
    'Gaudy Hat': '花哨之帽',
    'Gaudy Pants': '花哨裤子',
    'Gaudy Shirt': '花哨衬衫',
    'Generic Paperweight': '布鲁牌镇纸',
    'Ghost Typewriter': '幽灵打字机',
    'Ghostly Chest': '幽灵护胸',
    'Giant Alien Bug Nest': '巨型外星虫巢',
    'Giant Drumsticks': '巨型鼓槌',
    'Giant Sticky Foot': '巨大的粘粘脚玩具',
    'Giant Windup Gear': '巨型发条',
    'Gift Shop Buster Sword Replica': '破坏剑复制纪念品',
    'Gingerbread Boots': '姜饼靴子',
    'Gossamer Chest': '高斯魔的护胸',
    'Gouda Chestplate': '豪达奶酪护胸',
    'Gross Ring': '丑陋的戒指',
    'Groucho Marx Disguise': '格劳乔·马克斯的化装用具',
    'Hamlet': '小村庄',
    'Hat of Greed': '强欲之帽',
    'Havarti Ring': '哈瓦蒂干酪戒指',
    'Heart Shaped Panties': '心形内裤',
    'High Heeled Boots': '高跟鞋',
    'High Visibility Vest': '反光背心',
    'Infinity Charm': '无限护符',
    'King Looty': '战利品者之王',
    'Kokiri Blade': '科克里之刃',
    'Leather Jacket': '皮夹克',
    'Left Edgy Boot': '左边锐利靴子',
    'Left Fairy Wing': '左半边仙女翅膀',
    'Limburger Boots': '林堡干酪靴子',
    'Logs': '原木',
    'Looty McLootFace': '战利品者之脸',
    'LootzLrtozlOtZlOtTlooTTLoooLLLTTTToTlOOt': '战利品战品利战品战品战利品品战利利利战战战品品品品利品战利品',
    'Magic Bar Bar': '魔力条条',
    'Magicite Crystal': '魔导水晶',
    'Magitech Amulet': '魔导项链',
    'Magitech Blade': '魔导之刃',
    'Magitech Boots': '魔导靴子',
    'Magitech Chestplate': '魔导护胸',
    'Magitech Helmet': '魔导头盔',
    'Magitech Leggings': '魔导护腿',
    'Magitech Ring': '魔导戒指',
    'Mega Blue Jeans': '机甲蓝色牛仔裤',
    'Mega Boots': '机甲靴子',
    'Mega Chest': '机甲护胸',
    'Mega Helmet': '机甲头盔',
    'Mobster Hat': '匪帮之帽',
    'Mobster Pants': '匪帮裤子',
    'Mobster Vest': '匪帮马甲',
    'Mole Hammer': '鼹鼠锤',
    'Molotov Cocktail': '莫洛托夫鸡尾酒',
    'Mossy Ring': '青苔戒指',
    'My Blue Heart <3': '我的蓝色之心 <3',
    'My Brown Heart <3': '我的棕色之心 <3',
    'My Green Heart <3': '我的绿色之心 <3',
    'My Grey Heart <3': '我的灰色之心 <3',
    'My Orange Heart <3': '我的橙色之心 <3',
    'My Pink Heart <3': '我的粉色之心 <3',
    'My Purple Heart <3': '我的紫色之心 <3',
    'My Rainbow Heart': '我的彩虹之心',
    'My Red Heart <3': '我的红色之心 <3',
    'My Yellow Heart <3': '我的黄色之心 <3',
    'Neck Bolts': '颈螺栓',
    'Nerdy Shoes': '死宅之鞋',
    'No Pants': '无裤子',
    'Non Slip Shoes': '防滑鞋',
    'Not Drugs': '非毒品',
    'Not Sweat-Stained Underpants': '非汗渍内裤',
    'Numerical Boots': '数字靴子',
    'Numerical Chest': '数字护胸',
    'Numerical Head': '数字头盔',
    'Numerical Legs': '数字护腿',
    'Nunchuks': '双节棍',
    'Office Hat': '办公帽',
    'Office Pants': '办公裤子',
    'Office Shirt': '办公衬衫',
    'Office Shoes': '办公鞋',
    'Pants of Horror': '恐怖之裤',
    'Paper Fan': '布纸扇',
    'Paper Thin Crepe Cape': '布列塔尼可丽饼',
    'Party Hat': '派对帽',
    'Party Whistle': '派对吹吹卷',
    'Pirate Hat': '海盗帽',
    'Piratey Pants': '海盗裤子',
    'Piratey Peglegs': '海盗木腿',
    'Pizza Boots': '披萨靴子',
    'Plastic Red Cup': '塑料红杯',
    'Platform Boots': '松糕鞋',
    'Pocket Netherlands': '口袋式荷兰',
    'Pogmail Chest': '公仔纸护胸',
    'Polygon Boots': '多边形靴子',
    'Portable Stairway (To Heaven)': '便携式楼梯(通往天堂)',
    'Pretty Pink Slippers': '粉红拖鞋',
    'Rad Mixtape': '辐射混音带',
    'Random Crayons': '不明蜡笔',
    'Rare Foil Pokeyman Card': '宝基梦的稀有闪卡',
    'Raw Slab of Meat': '厚片生肉',
    'Raw Slab of Wood': '厚片生木',
    'Rectangle Pants': '长方形裤子',
    'Red Lipstick': '口红',
    'Red Meeple Thingy': '红色米宝',
    'Regular Pants': '普通裤子',
    'Rest of the Combat Cheese': '应战的奶酪剩余部分',
    'Right Edgy Boot': '右边锐利靴子',
    'Right Fairy Wing': '右半边仙女翅膀',
    'Ring of Apathy': '冷漠戒指',
    'Ring of Greed': '贪婪戒指',
    'Ring of Might': '力量戒指',
    'Ring of Utility': '多功能戒指',
    'Ring of Way Too Much Energy': '过多能量戒指',
    'Ring of Way Too Much Magic': '过多魔力戒指',
    'Rock Candy': '水晶糖',
    'Roller Skates': '旱冰鞋',
    'Rusty Sword': '生锈的剑',
    'SUPREME INTELLIGENCE LOOTY': '至高智慧战利品者',
    'School Jersey': '学校运动衫',
    'Seal of the Exile': '被流放者的封印',
    'Shoes With Wheels': '轮滑鞋',
    'Sir Looty McLootington III, Esquire': '战利品者三世爵士先生',
    'Skeleton Shirt': '骷髅衬衫',
    'Slimy Boots': '黏液靴子',
    'Slimy Chest': '黏液护胸',
    'Slimy Helmet': '黏液头盔',
    'Slimy Pants': '黏液裤子',
    'Slinky Boots': '彩虹圈靴子',
    'Some Duck-t Tape': '布基胶带',
    'Some Rolling Paper': '涂布卷烟纸',
    'Space Boots': '太空靴子',
    'Space Gun!': '太空神枪！',
    'Space Helmet': '太空头盔',
    'Space Suit Chest': '太空服护胸',
    'Space Suit Legs': '太空服护腿',
    'Spectral Boots': '幽鬼靴子',
    'Spinning Tophat': '旋转礼帽',
    'Spooky Sword': '惊骇之剑',
    'Spoopy Helmet': '悚乐头盔',
    'Square Chestpiece': '方之护胸',
    'Stapler': '订书机',
    'Stealthy Chest': '隐秘护胸',
    'Stealthy Hat': '隐秘之帽',
    'Steel Toed Boots': '钢趾靴',
    'Stonehenge Pants': '巨石阵裤子',
    'Stroopwaffel Pants': '焦糖华夫饼裤子',
    'Superior Japanese Katana': '高级武士刀',
    'Suspicious Sausage Necklace': '可疑的香肠项链',
    'Swashbuckler Chest': '海盗护胸',
    'Sweat-Stained NGU Shirt': '汗渍NGU衬衫',
    'Swiss Leggings': '瑞士干酪护腿',
    'THE CUBE': '立方体',
    'THE DEATHSTICK': '死亡棒',
    'THE MALF SLAMMER': 'MALF猛击者',
    'THE S': '字母S',
    'THRO, ODIGNSLUG': '尔托，奥丁恩蛞蝓',
    'Tear Away Pants': '梭织长裤',
    'Tentacle of the Exile': '被流放者的触须',
    'The Ass-cessory': '屁股饰品',
    'The Black Lotus': '黑莲花',
    'The Candy Cane of Destiny': '命运之糖杖',
    'The Credit Card': '信用卡',
    'The Cutlass': '海盗弯刀',
    'The D20': '二十面骰',
    'The D8': '八面骰',
    'The Disk of Dueling': '决斗盘',
    'The F Tank': 'F罐',
    'The Fists of Flubber': '飞天法宝之拳',
    'The Flintlock': '燧发枪',
    'The Glove of Power': '能量手套',
    'The Joker': '小王',
    'The Key': '吃豆人钥匙',
    'The Lonely Flubber': '孤独的飞天法宝',
    'The Number 7': '数字7',
    'The Pen-Is': '雕得一笔',
    'The Sands of Time': '时之沙',
    'The Six Shooter': '左轮手枪',
    'The Skip Card': '跳过牌',
    'The Stealthiest Armour': '最隐秘的护甲',
    'The Titan Effigy': '泰坦雕像',
    'The Toolbox': '工具箱',
    'The Triple Flubber': '三重飞天法宝',
    'The Tuba of Time': '时之大号',
    'The Zapper': '光枪',
    'Tie of Apathy': '冷漠领带',
    'Tommy Gun': '汤普森冲锋枪',
    'Trap Pants': '陷阱裤子',
    'ULTRAWIDE Pants': '超宽裤子',
    'Violin Case': '小提琴盒',
    'Weaponized Hollandaise sauce': '最终兵器荷兰酱',
    'Wee pin': '大头针',
    'Windmill Shirt': '风车衬衫',
    'Wooden Office Apron of Might': '木制办公力量围裙',
    'Yet Another Generic Pair Of Jeans': '另一条普通牛仔裤'
};

export function getItemNameCN(englishName) {
    return itemNamesCN[englishName] || englishName;
}

export function setItemNameMapping(englishName, chineseName) {
    itemNamesCN[englishName] = chineseName;
}

export function getItemNamesCN() {
    return itemNamesCN;
}

export default itemNamesCN;
